### ISSUE TITLE
log for tests hangs up

### ISSUE THREAD

**Issue by statistics101** [statistics101/scb2#21]
allTestsOrdered worked without log, printed %, but after introducing the log fine output, it freezes. On Boris's machine.

**Comment by statistics101** [comment]
Try to duplicate or fork the output to both console and log.

**Comment by statistics101** [comment]
it is possible that instead of appendage it did replacement? In the end the file is 
----------------- 
=====================
Test parameters : 
sampleSize=  6 
TParCount=  2 3 
Lag=  1 
replicationCount=  4 
superReplicationCount=  4 
nonCoverageProbability=  0.05 

 End of test testUtilTParCountBenchmarkFunction 
=========================================

**Comment by av1611** [comment]
implemented both in a loop and  via plyr::l_apply()

**Comment by statistics101** [comment]
Does not freeze anymore
