### ISSUE TITLE
4 Failed 

### ISSUE THREAD

**Issue by Avandres** [statistics101/scb2#32]
![image](https://user-images.githubusercontent.com/37335765/42038255-26f997ae-7af3-11e8-9157-fc6ffe6bee80.png)

**Comment by Avandres** [comment]
А. получил такой результат.

**Comment by ELWAHAB** [comment]
Вот какие тести били с ошибками 
Testing computeSqareRootBatchSizeUpperBound
Testing upperBoundLRVHatNorm
tests_prod2_027_computeUpperBoundSumNorm
tests_prod2_028

**Comment by statistics101** [comment]
Trace. Mismatched arguments
tests_prod2_025_computeSqareRootBatchSizeUpperBound
testUtilComputeSqareRootBatchSizeUpperBound
  upperBound <- computeSqareRootBatchSizeUpperBound(sigma = sigma,
                                                    index = index,
                                                    minIndex = minIndex)
computeSqareRootBatchSizeUpperBound <- function(sigma,
                                                minIndex,
                                                sampleSize)

**Comment by statistics101** [comment]
Закомментировали вызов тех, что баговали при индивидуальном вызове. Но 4 фейлд не ушло. Может это связано с версией тесттвета?
