### ISSUE TITLE
Bug prod2_025 and prod2_026, function  upperBoundLRVHatNorm 

### ISSUE THREAD

**Issue by ELWAHAB** [statistics101/scb2#33]
test_that(desc = "Testing computeSqareRootBatchSizeUpperBound",
          code = {
             testUtilComputeSqareRootBatchSizeUpperBound(sigma = 1,
                                                         sampleSize = 10,
                                                         minIndex = -5)
           }
 )
Error: Test failed: 'Testing computeSqareRootBatchSizeUpperBound'
* unused argument (sampleSize = 10)
1: .handleSimpleError(function (e) 
   {
       handled <<- TRUE
       test_error <<- e
       options(expressions = expressions_opt_new)
       on.exit(options(expressions = expressions_opt), add = TRUE)
       e$expectation_calls <- frame_calls(11, 2)
       test_error <<- e
       register_expectation(e)
       e$handled <- TRUE
       test_error <<- e
   }, "unused argument (sampleSize = 10)", quote(testUtilComputeSqareRootBatchSizeUpperBound(sigma = 1, 
       sampleSize = 10, minIndex = -5))) at :3
2: eval(code, test_env)

**Comment by statistics101** [comment]
Mismatched arguments

Trace
tests_prod2_025_computeSqareRootBatchSizeUpperBound
testUtilComputeSqareRootBatchSizeUpperBound
  upperBound <- computeSqareRootBatchSizeUpperBound(sigma = sigma,
                                                    index = index,
                                                    minIndex = minIndex)
computeSqareRootBatchSizeUpperBound <- function(sigma,
                                                minIndex,
                                                sampleSize)

**Comment by ELWAHAB** [comment]
Trace prod2_025
tests_prod2_025_computeSqareRootBatchSizeUpperBound -> 
testUtilComputeSqareRootBatchSizeUpperBound -> 
computeSqareRootBatchSizeUpperBound -> 
upperBoundLRVHatNorm (but this function don't finds) + ( разние аргументи
в подаче в функцию computeSqareRootBatchSizeUpperBound и имение в етой функцие аргументов
Подача
 upperBound <- computeSqareRootBatchSizeUpperBound(sigma = sigma,
                                                    index = index,
                                                    minIndex = minIndex)
Аргументи котории имеет функция

computeSqareRootBatchSizeUpperBound <- function(sigma,
                                                minIndex,
                                                sampleSize)  
 )

Trace prod2_026 
tests_prod2_026_upperBoundLRVHatNorm -> 
testUtilUpperBoundLRVHatNorm -> 
upperBoundLRVHatNorm (but this function don't finds)

Trace prod2_027 
tests_prod2_027_computeUpperBoundSumNorm -> 
testUtilComputeUpperBoundSumNorm ->
computeUpperBoundSumNorm (but this function don't finds)

Trace prod2_028
tests_prod2_028_createLambdaArrayForOBiid -> 
testUtilCreateLambdaArrayForOBiid -> 
createLambdaArrayForOBiid (but this function don't finds)

Если подвести итог нам нужно:
- написать функцию или найти upperBoundLRVHatNorm 
- написать функцию или найти computeUpperBoundSumNorm 
- написать функцию или найти createLambdaArrayForOBiid 
- Опредилить назначение функции computeSqareRootBatchSizeUpperBound  
и исправить ошибки с ее аргументами

**Comment by statistics101** [comment]
На момент написания, в следующих четырёх файлах присутствуют ошибки:

Первый файл:
файл tests_prod2_025_computeSqareRootBatchSizeUpperBound
Строка 5-ая вызывает функцию
testUtilComputeSqareRootBatchSizeUpperBound
Эта строка выдаёт ошибку, т.к. имена аргументов в самой функции
(sigma,
index,
minIndex)
Не соответствуют именам аргументов, используемым при вызове этой функции:
(sigma = 1,
sampleSize = 10,
minIndex = -5)
(Исправлено).
14-ая строка этой функции - вызов функции computeSqareRootBatchSizeUpperBound
В функции computeSqareRootBatchSizeUpperBound, в 23 строке вызывается функция upperBoundLRVHatNorm.
Такой функции не существует

Второй файл:
файл tests_prod2_026_upperBoundLRVHatNorm
Строка 6-ая вызывает файл из папки R:
testUtilUpperBoundLRVHatNorm.R
12-ая строка этого файла - вызов функции upperBoundLRVHatNorm
Такой функции не существует

Третий файл:
файл tests_prod2_027_computeUpperBoundLRVHatNorm
Строка 6-ая вызывает файл из папки R:
testUtilComputeUpperBoundSumNorm.R
14-ая строка этого файла - вызов функции computeSqareRootBatchSizeUpperBound
Такой функции не существует

Четвёртый файл:
файл tests_prod2_027_computeUpperBoundLRVHatNorm
Строка 6-ая вызывает файл из папки R:
testUtilCreateLambdaArrayForOBiid.R
13-ая строка этого файла - вызов функции createLambdaArrayForOBiid.
Такой функции не существует

Вариант решения проблемы один: написать необходимые функции. Ну, если пока что видеть сообщения об ошибках не хочется, можно на некоторое время отключить файлы от проекта.

**Comment by statistics101** [comment]
25 и 26 вызывают одну функцию, которой нет

**Comment by ELWAHAB** [comment]
Эту функцию мы решили закомментировать, а подальше, в случае необходимости придется написать.

**Comment by statistics101** [comment]
Закомментировали тут tests_prod2_025_computeSqareRootBatchSizeUpperBound
и тут tests_prod2_026_upperBoundLRVHatNorm

**Comment by Kosmos42** [comment]
Будет Необходимо заменить upperBoundLRVHatNorm
на computeUpperBound
Интерфейсы у них разные
нужно будет minIndex, sampleSize заменить на indexArray
нужно будет добавить type

**Comment by ELWAHAB** [comment]
Исправлено
