### ISSUE TITLE
Ошибки в тестах

### ISSUE THREAD

**Issue by Avandres** [statistics101/scb2#34]
На момент написания, в следующих четырёх файлах присутствуют ошибки:

Первый файл:
файл tests_prod2_025_computeSqareRootBatchSizeUpperBound
Строка 5-ая вызывает функцию
testUtilComputeSqareRootBatchSizeUpperBound
Эта строка выдаёт ошибку, т.к. имена аргументов в самой функции 
(sigma,
index,
minIndex)
Не соответствуют именам аргументов, используемым при вызове этой функции:
(sigma = 1,
sampleSize = 10,
minIndex = -5)
(Исправлено).
14-ая строка этой функции - вызов функции computeSqareRootBatchSizeUpperBound
В функции computeSqareRootBatchSizeUpperBound, в 23 строке вызывается функция upperBoundLRVHatNorm.
Такой функции не существует 

Второй файл:
файл tests_prod2_026_upperBoundLRVHatNorm
Строка 6-ая вызывает файл из папки R:
testUtilUpperBoundLRVHatNorm.R
12-ая строка этого файла - вызов функции upperBoundLRVHatNorm
Такой функции не существует 

Третий файл:
файл tests_prod2_027_computeUpperBoundLRVHatNorm
Строка 6-ая вызывает файл из папки R:
testUtilComputeUpperBoundSumNorm.R
14-ая строка этого файла - вызов функции computeSqareRootBatchSizeUpperBound
Такой функции не существует 

Четвёртый файл:
файл tests_prod2_027_computeUpperBoundLRVHatNorm
Строка 6-ая вызывает файл из папки R:
testUtilCreateLambdaArrayForOBiid.R
13-ая строка этого файла - вызов функции createLambdaArrayForOBiid.
Такой функции не существует 

Вариант решения проблемы один: написать необходимые функции. Ну, если пока что видеть сообщения об ошибках не хочется, можно на некоторое время отключить файлы от проекта.

**Comment by statistics101** [comment]
Дублируется. Закрываем
