### ISSUE TITLE
Bug prod2_028, function createLambdaArrayForOBiid 

### ISSUE THREAD

**Issue by ELWAHAB** [statistics101/scb2#36]
Trace prod2_028
tests_prod2_028_createLambdaArrayForOBiid ->
testUtilCreateLambdaArrayForOBiid ->
createLambdaArrayForOBiid (but this function don't finds)

We will must write function _createLambdaArrayForOBiid_

**Comment by ELWAHAB** [comment]
Эту функцию мы решили закомментировать, а подальше, в случае необходимости придется написать.

**Comment by statistics101** [comment]
Временно закомментировали тут tests_prod2_028_createLambdaArrayForOBiid

**Comment by ELWAHAB** [comment]
Нада изменить функцию createLambdaArrayForOBiid на  computeLambdaArray и поменять параметри, + в computeThetaArray нада изменить прийом типов для batchSize у верхней функции

**Comment by ELWAHAB** [comment]
![image](https://user-images.githubusercontent.com/25745274/42598507-1807f0fc-8565-11e8-895e-f30a104605d1.png)

![image](https://user-images.githubusercontent.com/25745274/42598486-0b32b948-8565-11e8-8f28-928ffc421477.png)
Исправлено
