### ISSUE TITLE
Тесты печатают номера, не соответствующие именам файлов

### ISSUE THREAD

**Issue by statistics101** [statistics101/scb2#37]
Подумать что делать. Как это часто встречается?

**Comment by ELWAHAB** [comment]
Файли при Ctr+Shift+T берутся в том порядке в котором они отсортировани в папке. Поскольку у нас 
файл на верху списка _tests_scb2_91_ThetaGraphics2dFixedBatchSize_ то и он же печатается первим. 
![image](https://user-images.githubusercontent.com/25745274/42598924-550b3602-8566-11e8-8206-00683d72f135.png)
В етом и заключается несоответствие между печатю некоторих тестов. Так же в тестах в которих есть префикс _tests_prod2_002_ печатаються без _prod2_ .
![image](https://user-images.githubusercontent.com/25745274/42599074-d47d000a-8566-11e8-8f6b-fd4c5bf50138.png) 
![image](https://user-images.githubusercontent.com/25745274/42599115-e95ee790-8566-11e8-8847-0cbb6f68d774.png)
![image](https://user-images.githubusercontent.com/25745274/42599154-088a5ee2-8567-11e8-8d26-245f40359d6f.png)
![image](https://user-images.githubusercontent.com/25745274/42599200-2a540938-8567-11e8-802b-09e917bcc009.png)
Причина найдена, в дальнейшем можна попитатся отсортировать тести, а сечас можна закрить эту тему.
