### ISSUE TITLE
allTestFilesManualOrdered обновить список

### ISSUE THREAD

**Issue by statistics101** [statistics101/scb2#38]

**Comment by ELWAHAB** [comment]
Вот такой сечас у нас список тестов, 
`tests_91_ThetaGraphics2dFixedBatchSize.R
tests_prod2_001_createCMatrix.R
tests_prod2_002_createDMatrix.R
tests_prod2_003_createOriginalCauchyDist.R
tests_prod2_004_createOriginalMA1.R
tests_prod2_004a_createOriginalMAInfConstCoef.R
tests_prod2_005_createOriginalMA1Replicated.R
tests_prod2_006_createGamma.R
tests_prod2_007_createRho.R
tests_prod2_008_createCenteredBernNoise.R
tests_prod2_009_createOriginalBernDens.R
tests_prod2_010_createOriginalXX.R
tests_prod2_011_createProductCol.R
tests_prod2_012_createProductColReplicated.r
tests_prod2_013_createLRVProductColl.R
tests_prod2_014_cutOB.R
tests_prod2_015_cutNB.R
tests_prod2_016_estimateLRVbyQuadraticForm.R
tests_prod2_017_computeQuadraticFormMatrixFromNB.R
tests_prod2_018_ComputeQuadraticFormValue.R
tests_prod2_019_computeQuadraticFormMatrixFromOB.R
tests_prod2_021_createBetaArray.R
tests_prod2_022_createBetaArrayReplicated.R
tests_prod2_023_ComputeBetaLRVArrayPsi0.R
tests_prod2_024_createOriginalXminusX.R
tests_prod2_025_computeSqareRootBatchSizeUpperBound.R
tests_prod2_026_upperBoundLRVHatNorm.R
tests_prod2_027_computeUpperBoundSumNorm.R
tests_prod2_028_createLambdaArrayForOBiid.R
tests_prod2_031_createCHatMatrix.R
tests_prod2_032_createDHatMatrix.R
tests_prod2_041_createLRVof2dArray.R
tests_prod2_042_createLRVof3dArray.R
tests_prod2_043_computeLRVofOB2dArray.R
tests_prod2_044_EstimateLRVWu2009ForCenteredSample.R
tests_prod2_044a_estimateWuForCenteredMAInfConstCoef.R
tests_prod2_045_EstimateLRVWu2009ForNonCenteredSample.R
tests_prod2_045a_estimateWuForNonCenteredMAInfConstCoef.R
tests_prod2_046_DrawWuForCentWithMA.R
tests_prod2_051_createDiffCMatrixVsCHatMatrix.R
tests_prod2_052_createDiffDMatrixVsDHatMatrix.R
tests_prod2_061_drawCVsCHat.R
tests_prod2_062_drawDVsDHat.R
tests_prod2_063_drawOriginalLrvHat.R
tests_prod2_064_drawVectorLrvVsLrvHat.R
tests_prod2_065_drawVectorLrvVsLrvHatForSize.R
tests_prod2_066_drawLrvHatVsTSAVsBasePeriodogram.R
tests_prod2_067_OBNBSizeCount.R
tests_prod2_068_FixSampleChangeProp.R
tests_prod2_069_ConstantProporsion.R
tests_prod2_070_LRVCompareNBMatrixToCutter.R
tests_prod2_071_saveProductCol.R
tests_prod2_072_saveJPG.R
tests_prod2_073_exportOriginal.R
tests_prod2_074_LRVCompareOBMatrixToCutter.R
tests_prod2_075_CompareLrvMatrixToCutterInType.R
tests_prod2_076_testUtilOBNBExpansion.R
tests_prod2_077_testUtilRenewalVSExpansion.R
tests_prod2_078_SavePlotWu2009EstimateLRV.R
tests_prod2_079_convertToSymMatrix.R
tests_prod2_081_benchmarkCreateOriginalMA1.R
tests_prod2_082_benchmarkCreateOriginalMA1Replicated.R
tests_prod2_083_BenchmarkCreateProductCol.R
tests_prod2_084_BenchmarkCreateCMatrix.R
tests_prod2_085_BenchmarkCreateDMatrix.R
tests_prod2_086_BenchmarkCreateBetaArray.R
tests_prod2_087_BenchmarkCreateBetaArrayReplicated.R
tests_prod2_088_BenchmarkCreateProductColReplicated.R
tests_prod2_089_BenchmarkCreateCHatMatrix.R
tests_prod2_090_BenchmarkCreateDHatMatrix.R
tests_prod2_091_BenchmarkCutNB.R
tests_prod2_092_BenchmarkCutOB.R
tests_prod2_093_BenchmarkComputeLRVofOB2dArray.R
tests_prod2_094_BenchmarkEstimateLRVbyQuadraticForm.R
tests_prod2_095_BenchmarkEstimateWuForNonCenterdSample.R
tests_prod2_096_BenchmarkEstimateWuForCenterdSample.R
tests_prod2_099_createDevStats.R
tests_prod2_100_drawMatrix.R
tests_prod2_101_wuForCenteredWithXminusX.R
tests_prod2_102_wuForCenteredWithXX.R
tests_prod2_103_WuForCentWithXXExpansion.R
tests_prod2_104_wuForCentWithXminusXExpansion.R
tests_prod2_105_wuForNonCentWithXX.R
tests_prod2_106_wuForNonCentWithXminusX.R
tests_prod2_107_wuForNonCentWithXXExpansion.R
tests_prod2_108_wuForNonCentWithXminusXExpansion.R
tests_scb_001_createTParArray.R
tests_scb_002_createTVMA1CoefArray.R
tests_scb_003_createNoise.R
tests_scb_004_createB.R
tests_scb_005_createSample.R
tests_scb_006_errorIfNotInputCompatible.R
tests_scb_011_normalDifferenceKernel.R
tests_scb_021_computeTermCount.R
tests_scb_022_computeLagCount.R
tests_scb_023_isLagCompatibleWithSampleSize.R
tests_scb_024_saveBandwith.R
tests_scb_025_isAlphaCompatibleWithSampleSiz.R
tests_scb_026_computeMaxLagForSampleSize.R
tests_scb_027_computeMinSampleSize.R
tests_scb_028_computeMinSampleSizeForAlpha.R
tests_scb_029_computeMinSampleSizeForBandwidth.R
tests_scb_031_computeCovHat.R
tests_scb_032_computeCorHat.R
tests_scb_033_computeAllCorHats.R
tests_scb_034_computeCor.R
tests_scb_035_computeGammaHat.R
tests_scb_041_computeBetaLRVHat.R
tests_scb_042_computeMEbyCovHat.R
tests_scb_051_createBand.R
tests_scb_052_createBandsBrick.R
tests_scb_061_computeIsCovered.R
tests_scb_062_computeIsCoveredArray.R
tests_scb_063_computeNonCoverageFreq.R
tests_scb_064_computeNonCoverageFreqArray.R
tests_scb_065_createNonCoverageFreqDoubleArray.R
tests_scb_071_saveBand.R
tests_scb_072_saveNonCoverageFreqArray.R
tests_scb_073_saveDoubleAplhaHatArray.R
tests_scb_074_saveMeForAlpha.R
tests_scb_075_saveMeArray3D.R
tests_scb_076_saveMeArray3DForBandwith.R
tests_scb_077_saveMeArray3DForSampleSize.R
tests_scb_078_saveAlphaHatOfSampleSize.R
tests_scb_079_saveBetaLRV.R
tests_scb_080_saveCorAndCorHat.R
tests_scb_081_saveMeForSampleSizeFunction.R
tests_scb_082_saveMeForBandwithFunction.R
tests_scb_083_testUtilSampleSizeBenchmarkFunction.R
tests_scb_084_testUtilReplicationCountBenchmark.R
tests_scb_085_testUtilSupeReplicationCountBenchmark.R
tests_scb_086_testUtilTparCountBenchmark.R
tests_scb2_100_testUtilObmLRVHatVarUpperBoundGraphics3d.R
tests_scb2_101_ObmLRVHatVarUpperBoundGraphics2dCurvilinear.R
tests_scb2_102_localLRV.R
tests_scb2_103_pcLocalLRVBandwidth.R
tests_scb2_104_nwLocalLRVBandwidth.R
tests_scb2_105_nwDenominatorBandwidthChange.R
tests_scb2_106_nwDenominatorMorePointsSameRange.R
tests_scb2_107_nwDenominatorMorePointsWiderRange.R
tests_scb2_108_nwDenominatorSmallerRange.R
tests_scb2_109_nwDenominatorUnevenPointDensity.R
tests_scb2_110_nwWeight.R
tests_scb2_111_thetaTypeAxis.R
tests_scb2_112_thetaTypeScaterplot.R
tests_scb2_113_thetaTypeDivision.R
tests_scb2_114_thetaTypeDivPower.R
tests_scb2_115_theta.R
tests_scb2_116_lambda.R
tests_scb2_117_capitalTheta.R
tests_scb2_117_capitalThetaTypeAxis.R
tests_scb2_118_capitalThetaTypeScaterplot.R
tests_scb2_119_capitalThetaTypeDivision.R
tests_scb2_120_capitalThetaTypeDivPower.R
tests_scb2_121_upperBound.R
tests_scb2_122_upperBoundAxis.R
tests_scb2_123_upperBoundScaterplot.R
tests_scb2_124_upperBoundDivision.R
tests_scb2_125_upperBoundDivPower.R
tests_scb2_126_An.R
tests_scb2_127_Bn.R
tests_scb2_128_Dn.R
tests_scb2_129_AnDivBn.R
tests_scb2_130_ThetaVsCapitalThetaType.R
tests_scb2_131_BetaNonRadomOriginal1.R
tests_scb2_132_BetaNonRadomOriginalI.R
tests_scb2_133_BetaSumOfNAEntries.R
tests_scb2_134_BetaLRVAndBetaLRVHat.R
tests_scb2_135_BetaLRVAndBetaLRVHatGrowSize.R
tests_scb2_136_BenchmarkBetaLRVAndBetaLRVHatGrowSize.R
tests_scb2_137_BenchmarkBetaLRVAndBetaLRVHat.R
tests_scb2_138_BetaLRVAndBetaLRVHatGrowSizeExpansion.R
tests_scb2_139_BetaHatNonRadomOriginal1.R
tests_scb2_140_BetaHatNonRadomOriginalI.R
tests_scb2_141_BetaHatSumOfNAEntries.R
tests_scb2_142_BetaHatLRVHatAndBetaLRVHat.R
tests_scb2_143_ProductSampleAndGammaHat.R
tests_scb2_144_BetaHatAndBeta.R
tests_scb2_90_ThetaGraphics3d.R
tests_scb2_91_ThetaGraphics2dFixedBatchSize.R
tests_scb2_92_ThetaGraphics2dFixedIndex.R
tests_scb2_93_ThetaGraphics2dCurvilinear.R
tests_scb2_94_LambdaGraphics3d.R
tests_scb2_95_LambdaGraphics2dFixedBatchSize.R
tests_scb2_96_LambdaGraphics2dFixedIndex.R
tests_scb2_97_LambdaGraphics2dCurvilinear.R
tests_scb2_98_testUtilsumSqBlockSumsVarUpperBoundGraphics3d.R
tests_scb2_99_SumSqBlockSumsVarUpperBoundGraphics2dCurvilinear.R`

Их насчитывается 188 тестов

Из них было записанов в функцию allTestFilesManualOrdered.Р только 147 тестов
`tests_prod2_001_createCMatrix.R
tests_prod2_002_createDMatrix.R
tests_prod2_003_createOriginalCauchyDist.R
tests_prod2_004_createOriginalMA1.R
tests_prod2_004a_createOriginalMAInfConstCoef.R
tests_prod2_005_createOriginalMA1Replicated.R
tests_prod2_006_createGamma.R
tests_prod2_007_createRho.R
tests_prod2_008_createCenteredBernNoise.R
tests_prod2_009_createOriginalBernDens.R
tests_prod2_010_createOriginalXX.R
tests_prod2_011_createProductCol.R
tests_prod2_013_createLRVProductColl.R
tests_prod2_014_cutOB.R
tests_prod2_015_cutNB.R
tests_prod2_016_estimateLRVbyQuadraticForm.R
tests_prod2_017_computeQuadraticFormMatrixFromNB.R
tests_prod2_018_ComputeQuadraticFormValue.R
tests_prod2_019_computeQuadraticFormMatrixFromOB.R
tests_prod2_021_createBetaArray.R
tests_prod2_022_createBetaArrayReplicated.R
tests_prod2_023_ComputeBetaLRVArrayPsi0.R
tests_prod2_024_createOriginalXminusX.R
tests_prod2_025_computeSqareRootBatchSizeUpperBound.R
tests_prod2_026_upperBoundLRVHatNorm.R
tests_prod2_027_computeUpperBoundSumNorm.R
tests_prod2_028_createLambdaArrayForOBiid.R
tests_prod2_031_createCHatMatrix.R
tests_prod2_032_createDHatMatrix.R
tests_prod2_041_createLRVof2dArray.R
tests_prod2_042_createLRVof3dArray.R
tests_prod2_043_computeLRVofOB2dArray.R
tests_prod2_044_EstimateLRVWu2009ForCenteredSample.R
tests_prod2_044a_estimateWuForCenteredMAInfConstCoef.R
tests_prod2_045_EstimateLRVWu2009ForNonCenteredSample.R
tests_prod2_045a_estimateWuForNonCenteredMAInfConstCoef.R
tests_prod2_046_DrawWuForCentWithMA.R
tests_prod2_051_createDiffCMatrixVsCHatMatrix.R
tests_prod2_052_createDiffDMatrixVsDHatMatrix.R
tests_prod2_061_drawCVsCHat.R
tests_prod2_062_drawDVsDHat.R
tests_prod2_063_drawOriginalLrvHat.R
tests_prod2_064_drawVectorLrvVsLrvHat.R
tests_prod2_065_drawVectorLrvVsLrvHatForSize.R
tests_prod2_066_drawLrvHatVsTSAVsBasePeriodogram.R
tests_prod2_067_OBNBSizeCount.R
tests_prod2_068_FixSampleChangeProp.R
tests_prod2_069_ConstantProporsion.R
tests_prod2_070_LRVCompareNBMatrixToCutter.R
tests_prod2_071_saveProductCol.R
tests_prod2_072_saveJPG.R
tests_prod2_073_exportOriginal.R
tests_prod2_074_LRVCompareOBMatrixToCutter.R
tests_prod2_075_CompareLrvMatrixToCutterInType.R
tests_prod2_076_testUtilOBNBExpansion.R
tests_prod2_077_testUtilRenewalVSExpansion.R
tests_prod2_078_SavePlotWu2009EstimateLRV.R
tests_prod2_079_convertToSymMatrix.R
tests_prod2_081_benchmarkCreateOriginalMA1.R
tests_prod2_082_benchmarkCreateOriginalMA1Replicated.R
tests_prod2_083_BenchmarkCreateProductCol.R
tests_prod2_084_BenchmarkCreateCMatrix.R
tests_prod2_085_BenchmarkCreateDMatrix.R
tests_prod2_086_BenchmarkCreateBetaArray.R
tests_prod2_087_BenchmarkCreateBetaArrayReplicated.R
tests_prod2_088_BenchmarkCreateProductColReplicated.R
tests_prod2_089_BenchmarkCreateCHatMatrix.R
tests_prod2_090_BenchmarkCreateDHatMatrix.R
tests_prod2_091_BenchmarkCutNB.R
tests_prod2_092_BenchmarkCutOB.R
tests_prod2_093_BenchmarkComputeLRVofOB2dArray.R
tests_prod2_094_BenchmarkEstimateLRVbyQuadraticForm.R
tests_prod2_095_BenchmarkEstimateWuForNonCenterdSample.R
tests_prod2_096_BenchmarkEstimateWuForCenterdSample.R
tests_prod2_099_createDevStats.R
tests_prod2_100_drawMatrix.R
tests_prod2_101_wuForCenteredWithXminusX.R
tests_prod2_102_wuForCenteredWithXX.R
tests_prod2_103_WuForCentWithXXExpansion.R
tests_prod2_104_wuForCentWithXminusXExpansion.R
tests_prod2_105_wuForNonCentWithXX.R
tests_prod2_106_wuForNonCentWithXminusX.R
tests_prod2_107_wuForNonCentWithXXExpansion.R
tests_prod2_108_wuForNonCentWithXminusXExpansion.R
tests_scb_001_createTParArray.R
tests_scb_002_createTVMA1CoefArray.R
tests_scb_003_createNoise.R
tests_scb_004_createB.R
tests_scb_005_createSample.R
tests_scb_006_errorIfNotInputCompatible.R
tests_scb_011_normalDifferenceKernel.R
tests_scb_021_computeTermCount.R
tests_scb_022_computeLagCount.R
tests_scb_023_isLagCompatibleWithSampleSize.R
tests_scb_024_saveBandwith.R
tests_scb_025_isAlphaCompatibleWithSampleSiz.R
tests_scb_026_computeMaxLagForSampleSize.R
tests_scb_027_computeMinSampleSize.R
tests_scb_028_computeMinSampleSizeForAlpha.R
tests_scb_029_computeMinSampleSizeForBandwidth.R
tests_scb_031_computeCovHat.R
tests_scb_032_computeCorHat.R
tests_scb_033_computeAllCorHats.R
tests_scb_034_computeCor.R
tests_scb_035_computeGammaHat.R
tests_scb_041_computeBetaLRVHat.R
tests_scb_042_computeMEbyCovHat.R
tests_scb_051_createBand.R
tests_scb_052_createBandsBrick.R
tests_scb_061_computeIsCovered.R
tests_scb_062_computeIsCoveredArray.R
tests_scb_063_computeNonCoverageFreq.R
tests_scb_064_computeNonCoverageFreqArray.R
tests_scb_065_createNonCoverageFreqDoubleArray.R
tests_scb_071_saveBand.R
tests_scb_072_saveNonCoverageFreqArray.R
tests_scb_073_saveDoubleAplhaHatArray.R
tests_scb_074_saveMeForAlpha.R
tests_scb_075_saveMeArray3D.R
tests_scb_076_saveMeArray3DForBandwith.R
tests_scb_077_saveMeArray3DForSampleSize.R
tests_scb_078_saveAlphaHatOfSampleSize.R
tests_scb_079_saveBetaLRV.R
tests_scb_080_saveCorAndCorHat.R
tests_scb_081_saveMeForSampleSizeFunction.R
tests_scb_082_saveMeForBandwithFunction.R
tests_scb_083_testUtilSampleSizeBenchmarkFunction.R
tests_scb_084_testUtilReplicationCountBenchmark.R
tests_scb_085_testUtilSupeReplicationCountBenchmark.R
tests_scb_086_testUtilTparCountBenchmark.R
tests_scb2_104_nwLocalLRVBandwidth.R
tests_scb2_105_nwDenominatorBandwidthChange.R
tests_scb2_106_nwDenominatorMorePointsSameRange.R
tests_scb2_107_nwDenominatorMorePointsWiderRange.R
tests_scb2_108_nwDenominatorSmallerRange.R
tests_scb2_109_nwDenominatorUnevenPointDensity.R
tests_scb2_110_nwWeight.R
tests_scb2_90_ThetaGraphics3d.R
tests_scb2_91_ThetaGraphics2dFixedBatchSize.R
tests_scb2_92_ThetaGraphics2dFixedIndex.R
tests_scb2_93_ThetaGraphics2dCurvilinear.R
tests_scb2_94_LambdaGraphics3d.R
tests_scb2_95_LambdaGraphics2dFixedBatchSize.R
tests_scb2_96_LambdaGraphics2dFixedIndex.R
tests_scb2_97_LambdaGraphics2dCurvilinear.R
tests_scb2_98_testUtilsumSqBlockSumsVarUpperBoundGraphics3d.R
tests_scb2_99_SumSqBlockSumsVarUpperBoundGraphics2dCurvilinear.R`

Я в свою очередь нашел 41 тест, который не был добавлен и соответственно добавил их
`tests_91_ThetaGraphics2dFixedBatchSize.R
tests_prod2_012_createProductColReplicated.r
tests_scb2_100_testUtilObmLRVHatVarUpperBoundGraphics3d.R
tests_scb2_101_ObmLRVHatVarUpperBoundGraphics2dCurvilinear.R
tests_scb2_102_localLRV.R
tests_scb2_103_pcLocalLRVBandwidth.R
tests_scb2_111_thetaTypeAxis.R
tests_scb2_112_thetaTypeScaterplot.R
tests_scb2_113_thetaTypeDivision.R
tests_scb2_114_thetaTypeDivPower.R
tests_scb2_115_theta.R
tests_scb2_116_lambda.R
tests_scb2_117_capitalTheta.R
tests_scb2_117_capitalThetaTypeAxis.R
tests_scb2_118_capitalThetaTypeScaterplot.R
tests_scb2_119_capitalThetaTypeDivision.R
tests_scb2_120_capitalThetaTypeDivPower.R
tests_scb2_121_upperBound.R
tests_scb2_122_upperBoundAxis.R
tests_scb2_123_upperBoundScaterplot.R
tests_scb2_124_upperBoundDivision.R
tests_scb2_125_upperBoundDivPower.R
tests_scb2_126_An.R
tests_scb2_127_Bn.R
tests_scb2_128_Dn.R
tests_scb2_129_AnDivBn.R
tests_scb2_130_ThetaVsCapitalThetaType.R
tests_scb2_131_BetaNonRadomOriginal1.R
tests_scb2_132_BetaNonRadomOriginalI.R
tests_scb2_133_BetaSumOfNAEntries.R
tests_scb2_134_BetaLRVAndBetaLRVHat.R
tests_scb2_135_BetaLRVAndBetaLRVHatGrowSize.R
tests_scb2_136_BenchmarkBetaLRVAndBetaLRVHatGrowSize.R
tests_scb2_137_BenchmarkBetaLRVAndBetaLRVHat.R
tests_scb2_138_BetaLRVAndBetaLRVHatGrowSizeExpansion.R
tests_scb2_139_BetaHatNonRadomOriginal1.R
tests_scb2_140_BetaHatNonRadomOriginalI.R
tests_scb2_141_BetaHatSumOfNAEntries.R
tests_scb2_142_BetaHatLRVHatAndBetaLRVHat.R
tests_scb2_143_ProductSampleAndGammaHat.R
tests_scb2_144_BetaHatAndBeta.R`

**Comment by statistics101** [comment]
Done
