### ISSUE TITLE
tests_scb2_117_capitalThetaTypeAxis и функция  computeCapitalThetaArray 

### ISSUE THREAD

**Issue by ELWAHAB** [statistics101/scb2#39]
Trace 
tests_scb2_117_capitalThetaTypeAxis -> 
testUtilCapitalThetaTypeAxis -> 
computeCapitalThetaArray-> 
computeThetaArray  

 
В функции  computeCapitalThetaArray используется достаточно большое значение,
 и может тормозить проверку тестов. Вот следующий код

> computeCapitalThetaArray <- function(indexArray,
>                                      sigma,
>                                      type = "X",
>                                      ...)
> {
>   bigFakeInf <-  100000
>   bigFakeInfIndexArray <- 0:bigFakeInf
> 
>   bigFakeInfLambda<- sum(computeThetaArray(indexArray = bigFakeInfIndexArray,
>                                             sigma = sigma,
>                                             type = type,
>                                             ... = ...))
> 
>   thetaArray <- computeThetaArray(indexArray = indexArray,
>                                   sigma = sigma,
>                                   type = type,
>                                   ... = ...)
>   capitalThetaArray <- array(dim = length(indexArray))
>   capitalTheta <- bigFakeInfLambda
>   for(indexCTheta in 1:length(indexArray))
>   {
>     capitalTheta <- capitalTheta - thetaArray[indexCTheta]
>     capitalThetaArray[indexCTheta] <- capitalTheta
>   }
>   return(capitalThetaArray)
> } 

Здесь у нас переменая bigFakeInf   имеет значение 100000 . 

Мне кажется, что у Б. при Ctr+shift+t может подвисать и через етот тест.

**Comment by Avandres** [comment]
Также, при запуске этого теста выдаётся следующая ошибка:
![_tests_scb2_117_capitalthetatypeaxis](https://user-images.githubusercontent.com/37335765/42187807-0fdb42ba-7e5a-11e8-8518-b4e70522bebd.png)

**Comment by Avandres** [comment]
Ошибка в 55-ой строке функции testUtilCapitalThetaTypeAxis. Вместо переменной subTitle должна использоваться переменная subTitleType2

**Comment by ELWAHAB** [comment]
Исправлено
